
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: Voda0763
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: writehub_development

test:
  <<: *default
  database: writehub_test
#
production:
  <<: *default
  database: writehub_production
  username: postgres
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  port: 5433
  host: 45.92.9.7
