
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: postgres
  password: Voda0763
  host: localhost
  database: writehub_development
  
# Do not set this db to the same as development or production.
test:
  <<: *default
  username: postgres
  password: Voda0763
  host: localhost
  database: writehub_test

#
production:
  <<: *default
  database: writehub_production
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  url: <%= ENV["DB_HOST"] %>
