service: linodeblog
image: ibunhabibu/writehub:latest
servers:
  web:
     hosts:
      - 45.92.9.7
    labels:
      traefik.http.routers.mynewapp.rule: Host(`mynewapp.com`)
      traefik.http.routers.mynewapp.entrypoints: websecure
      traefik.http.routers.mynewapp_secure.rule: Host(`mynewapp.com`)
      traefik.http.routers.mynewapp_secure.tls: true
      traefik.http.routers.mynewapp_secure.tls.certresolver: letsencrypt
    options:
      network: "private"
env:
  - RAILS_ENV=production
  - DATABASE_URL=postgresql://postgres:Voda0763@db_host/linodeblog
  - SECRET_KEY_BASE=SECRET_KEY_BASE

registry:
<<<<<<< HEAD
  username: ibunhabibu
  password: KAMAL_REGISTRY_PASSWORD
=======
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD
# Inject ENV variables into containers (secrets come from .env).
# Remember to run `kamal env push` after making changes!
env:
  clear:
    RAILS_ENV: production
    RACK_ENV: production
    RAILS_LOG_TO_STDOUT: true
    RAILS_SERVE_STATIC_FILES: true
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_USER
    - POSTGRES_PASSWORD
>>>>>>> 83dec71 (Add environment)
