
service: writehub

image: ibunhabibu/writehub

servers:
  web:
    - 45.92.9.7
proxy: 
  ssl: true
  host: writehub.cyou
  app_port: 3000

# Credentials for your image host.
registry:
  username: ibunhabibu
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64

env:
  clear:
    DB_HOST: writehub-db
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - GOOGLE_API
    - PIXABAY
    - OPEN_WEATHER

ssh:
  user: deployer

accessories:
  db:
    image: postgres:15
    host: 45.92.9.7
    port: "127.0.0.1:5434:5434"  # Ensure this is the correct port or change it to 5432 if needed
    env:
      clear:
        POSTGRES_USER: 'postgres'
        POSTGRES_DB: 'writehub_production'
      secret:
        - POSTGRES_USER
        - POSTGRES_PASSWORD
    files:
      - config/init.sql:/docker-entrypoint-initdb.d/setup.sql
