# Name of your application. Used to uniquely configure containers.
service: contaborails

# Name of the container image.
image: ibunhabibu/contaborails

# Deploy to these servers.
servers:
  web:
    - 45.92.9.7

proxy: 
  ssl: true
  host: habibtech.online
  # Proxy connects to your container on port 80 by default.
  app_port: 3000

# Credentials for your image host.
registry:
  username: ibunhabibu
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64

env:
  clear:
    DB_HOST: 45.92.9.7
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_USER
    - POSTGRES_PASSWORD


ssh:
  user: deployer

accessories:
  db:
    image: postgres:15
    host: 45.92.9.7
    port: 5433:5433  # Ensure this is the correct port or change it to 5432 if needed
    env:
      clear:
        POSTGRES_USER: 'postgres'
        POSTGRES_DB: 'writehub_production'
      secret:
        - POSTGRES_USER
        - POSTGRES_PASSWORD
    files:
      - config/init.sql:/docker-entrypoint-initdb.d/setup.sql
