# Name of your application. Used to uniquely configure containers.
service: writehub

# Name of the container image.
image: ibunhabibu/writehub
# Deploy to these servers.
servers:
  web:
    hosts:
      - 139.162.238.85
    labels:
      traefik.http.routers.mynewapp.rule: Host(`habibtech.online`)
      traefik.http.routers.mynewapp.entrypoints: websecure
      traefik.http.routers.mynewapp_secure.rule: Host(`habibtech.online`)
      traefik.http.routers.mynewapp_secure.tls: true
      traefik.http.routers.mynewapp_secure.tls.certresolver: letsencrypt
    options:
      network: "private"

# Credentials for your image host.
registry:
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .env).
# Remember to run `kamal env push` after making changes!
env:
  clear:
    RAILS_ENV: production
    RACK_ENV: production
    RAILS_LOG_TO_STDOUT: true
    RAILS_SERVE_STATIC_FILES: true
  secret:
    - RAILS_MASTER_KEY
    - SECRET_KEY_BASE
    # - DB_HOST
    - POSTGRES_USER
    - POSTGRES_PASSWORD

# Use a different ssh user than root
ssh:
  user: deployer

# Configure builder setup.
# builder:
#   remote:
#     arch: amd64

# Use accessory services (secrets come from .env).
accessories:
  db:
    image: postgres:16.0
    host: 139.162.238.85
    env:
      clear:
        POSTGRES_USER: POSTGRES_USER
        POSTGRES_DB: 'writehub_production'
      secret:
        - POSTGRES_PASSWORD
        - POSTGRES_USER
    files:
      - config/init.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - data:/var/lib/postgresql/data
    options:
      network: "private"

traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json"
    network: "private"
  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    entryPoints.web.http.redirections.entryPoint.to: websecure
    entryPoints.web.http.redirections.entryPoint.scheme: https
    entryPoints.web.http.redirections.entrypoint.permanent: true
    certificatesResolvers.letsencrypt.acme.email: "ibunhabib@gmail.com"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web

asset_path: /rails/public/assets